      - name: Download and Prepare Sing-box Core
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          
          TAG_NAME=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r '.tag_name')
          VERSION=${TAG_NAME#v}
          
          echo "📥 Downloading Sing-box Android v$VERSION..."
          # تغییر لینک از linux-arm64 به android-arm64
          curl -L -o singbox-arm64.tar.gz "https://github.com/SagerNet/sing-box/releases/download/${TAG_NAME}/sing-box-${VERSION}-android-arm64.tar.gz"
          tar -xzf singbox-arm64.tar.gz
          
          # تغییر مسیر جابجایی پوشه به نسخه اندروید
          mv sing-box-${VERSION}-android-arm64/sing-box app/src/main/jniLibs/arm64-v8a/libsingbox.so
          
          echo "✅ Android Core binary packaged successfully!"
          
